.. -*- coding: utf-8 -*-

=========================================
Computergestützte Mathematik zur Analysis
=========================================

-------------------------------------------------------------------
Übersicht über die verwendeten Befehle, nach Lektionen geordnet
-------------------------------------------------------------------

.. contents:: Inhaltsverzeichnis
              :backlinks: none

Lektion 1
*********

initialer Import
================

+     ``from sympy import *``

      Import der Bibliothek

+     ``init_printing()``

      Einschalten der aufgehübschten Ausgabe

      
Arithmetik
==========

+     Befehle werden mit ``;``
      oder ``:`` abgeschlossen.  Im
      ersten Fall wird das Ergebnis angezeigt, im zweiten nicht.  
      Zeilenende impliziert ``;``

+     ``+, -, *, /, **``

      arithmetische Operatoren


Symbolische Rechnung
====================

+     ``=``

      Zuweisung

+     ``==``

      Vergleichsoperator (später)

+     ``Rational``
	    
      rationale Zahl (im Gegensatz zur Fließkommazahl)

beliebig genaue Fließkommazahlen
================================

+     ``pi``

      Kreiszahl 

+     ``N''
	    
      numerische Auswertung (Funktion) siehe auch in `bestimmte Integrale`_

+     ``print``

      einfache Ausgabe

      

Sympyfizierungen
================

+     ``S``

      verwandelt allgemeines Python-Objekt in ``sympy``-Objekt, falls
      das sinnvoll ist

+     ``type``

      Typ eines Ausdrucks



Symbole
=======

+     ``x = S('x')``

      Einrichtung eines Symbols

+     ``x = Symbol('x')``

      alternative


elementare Funktionen
=====================

+     ``sqrt``

      Quadratwurzel

+     ``sin, cos, tan, cot``

      trigonometrische Funktionen

+     ``asin, acos, atan, acot``

      inverse trigonometrische Funktionen

#..      ``arctan`` siehe auch in `Der Arcustangens`_

+     ``log, ln``

      natürlicher Logarithmus

+     ``exp``

      Exponentialfunktion

+     ``abs``

      Absolutbetrag	    

+     ``?``

      Hilfe zu einem Befehl	    
      
zurück zum Inhaltsverzeichnis_



Lektion 2
*********

Vereinfachungen
===============

+ ``expand``

  Ausmultiplikation (Methode und Funktion)

+ ``factor``
  
  Faktorisierung von Polynomen (Methode und Funktion)

+ ``ratsimp``

  Vereinfachung von Brüchen (Methode und Funktion)

+ ``trigsimp``

  Vereinfachung trigonometrischer Ausdrücke (Methode und Funktion)

+ ``simplify``

  alle sinnvollen Vereinfachungen (Methode und Funktion)
  
Auswertung von Ausdrücken
=========================

+ ``subs``

  Ersetzung eines Teilausdrucks (Methode)

Grenzwerte
==========

+ ``limit``

  Grenzwert (Methode und Funktion)

+ ``Limit``

  träger Grenzwert (Funktion)

+ ``doit``

  Ausführung einer trägen Ausdrucks (Methode)

+ ``factorial``

  Fakultät

Ableitungen
===========

+ ``diff``

  Ableitung (Methode und Funktion)

+ ``numer``

  Zähler (Funktion)

+ ``denom``

  Nenner (Funktion)

unbestimmte Integrale
=====================

+ ``integrate``

  Integral (Methode und Funktion) siehe auch `bestimmte Integrale`_

bestimmte Integrale
===================

+ ``integrate``

  Integral (Methode und Funktion) siehe auch `unbestimmte Integrale`_

+ ``Integral``

  träger Operator (Funktion)

+ ``n``

  numerische Auswertung (Methode) siehe auch in `beliebig genaue Fließkommazahlen`_


zurück zum Inhaltsverzeichnis_


  
  
----------------------

© 2016 `Rüdiger Braun`_

zurück zum Inhaltsverzeichnis_

.. _`Rüdiger Braun`: mailto:Ruediger.Braun@uni-duesseldorf.de
